# Generated by Django 3.2.8 on 2021-10-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_auto_20211024_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='meeting_room',
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_room',
            field=models.ManyToManyField(to='meetings.MeetingRoom'),
        ),
    ]
