# Generated by Django 3.2.8 on 2021-10-24 18:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0004_auto_20211024_1731'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Organizer',
        ),
    ]
