# Generated by Django 3.2.8 on 2021-10-25 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_rename_userprofile_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='meeting_room',
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='meetings.meetingroom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meetings.organizer'),
        ),
    ]
