# Generated by Django 3.2.8 on 2021-10-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_auto_20211024_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='last_training_date',
            field=models.DateField(default=0, null=True),
        ),
    ]
