# Generated by Django 3.2.8 on 2021-10-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_alter_visitor_last_training_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='last_training_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
