# Generated by Django 3.2.8 on 2021-10-25 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_auto_20211025_1744'),
        ('visitors', '0005_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meetings.organizer')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visitors.visitor')),
            ],
        ),
    ]
